export const SET_IS_FETCHING_MOVIE = 'SET_IS_FETCHING_MOVIE';
export const SET_IS_FETCHING_CHARACTER = 'SET_IS_FETCHING_CHARACTER ';
export const SET_IS_FETCHING_DETAIL_CHARACTER =
  'SET_IS_FETCHING_DETAIL_CHARACTER';
export const GET_CHARACTER_DATA = 'GET_CHARACTER_DATA';
export const GET_DETAIL_CHARACTER_DATA = 'GET_DETAIL_CHARACTER_DATA';
export const GET_MOVIE_DATA = 'GET_MOVIE_DATA';
